name: Local
variables:
  - name: BASE_URL
    value: http://localhost:8001/api/v1
  - name: to_pair_session_id
    value: 7d8a1f95-be04-4adf-9390-000fdb079a0c
  - name: admin_access_token
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2MzQ2MWJjOC04ZDNmLTQ0YTgtYTJmMS0yNDNjNzk0MDQyNTUiLCJzdWIiOiIxIiwidHlwZSI6ImFjY2VzcyIsImV4cCI6MTc4NTg1MjUyNywicm9sZSI6ImFkbWluIn0.GCigg9y_Ym2FZeb8QDvSjjxjpi6Htpgzr-Pb7bxyR7BRJWIESpq0c02bPcadjKu41-laoqDMlUA-R2EXj4GCrdEghlBtwgkqX32eF3jR6BL_yxuCEw_lOgsah9aRl9GM-WAWPV69P7qL2WU5G5KvTgXSpx2AhJ5mrMVZeGSqc6EnveYuQ5Wb6YAYjHP2DTZzH8Xl6hnbrHep8JuIkVuJOw2Lu-pjj4vjinw8UJUzRFqpL5vVeI3Q0NeS4OoG3ykvIAg2gJQC2g6f6mogXCqxDyLANaAyNZK_QS6DEj-ZyoMyPhU_Tp9dpcTNCOusHSBO7Ib_vPHVZg2A_ZP4pIBppg
  - name: access_token
    value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uX2lkIjoiOWQwNjYxZjEtN2UwZS00MjY5LWI4ZDctY2I1MTcwMTM1ZjE1IiwidXNlcl9pZCI6Ik5vbmUiLCJqdGkiOiJlYzY0OWI1YS0wM2RkLTQ2NGUtYTNhNS0xZGI4Nzk0ZDE5MzYiLCJ0eXBlIjoiYWNjZXNzIn0.JC88SWdPQbm9twI_8m156v6Ee9xNrg7kLESzVZjn19eFLAW17icKp_SCtTHAes5TuooEdc6mmdmFt3C9LQTFiDQyaKw3PMD4HH-lrTTobbvDj2etR7IkZIRYmUdKNMLMIvRFrNqZ_7DHzxHPl3nJ5t6yAvd0_j9wReDL8IbuIegPo_S9IZ7TAOyIY83b64uoco3395Y4tohAm_B15nP5k_jUmL6SgwVs6n5Zj3qX2EZPYg9zjVSpvn4noXJwkIKZ1GQ0U33ndROwZ7mKeajich56Kv8tH8bNlg5BiUMxUaPjeneQizgA6gNyLFBmKIzLMT_hU7G73YJK2-g0RNLpjA
  - name: session_id
    value: 7b15c0b3-6ced-4a5f-af71-f2241c353170
  - name: file_url
    value: https://clip-cloud.s3.ru-3.storage.selcloud.ru/rooms/05edfda1-bc25-4c04-a629-0bd6e7a52259/files/3f384401-d2b4-4c26-b328-eadb916d0865?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ea20c533953f416693b919cac94b859f%2F20260810%2Fru-3%2Fs3%2Faws4_request&X-Amz-Date=20260810T090858Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=8c88f8ebafe4094d61a80b985c110d095435edbe4c3ea653f4037ace9877ac78
  - name: file_id
    value: b8aa31f8-e7ac-4c6b-b20f-b1c8f07e6a14
  - name: load_file_id
    value: b8aa31f8-e7ac-4c6b-b20f-b1c8f07e6a14
  - name: load_file_url
    value: https://clip-cloud.s3.ru-3.storage.selcloud.ru/7ea71ff5-8bd1-4adf-88c6-df9d496b1227?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ea20c533953f416693b919cac94b859f%2F20260810%2Fru-3%2Fs3%2Faws4_request&X-Amz-Date=20260810T090952Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=288c343d6dcaf08e3f882f329cd2b6cf37d5969b968f4f54e3318d80393f9795
  - name: upload_url
    value: https://clip-cloud.s3.ru-3.storage.selcloud.ru/rooms/6c3c2561-44f1-4dc4-8074-4ebdc7e7b5dd/files/db927a31-3bc1-44bc-95a7-53ee65b4ce81?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ea20c533953f416693b919cac94b859f%2F20260810%2Fru-3%2Fs3%2Faws4_request&X-Amz-Date=20260810T125124Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=ccfc889943d663d7769a53628c05ab3982e9c93a7c274e7a807e44cd106b94f5
  - name: message_id
    value: c6b14dce-61e2-405c-ab3f-88af5a30a2d6
  - name: room_code
    value: UFAJB
